version: "3"
services:
  ecmdb-web:
    restart: always
    container_name: ecmdb-web
    image: registry.cn-qingdao.aliyuncs.com/duke1616/ecmdb-web:main
    ports:
      - "8888:8000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    name: ecmdb
    external: true
