/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"404" | "api" | "bug" | "component" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task" | "template" | "unocss" | "user" | "worker">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"404" | "api" | "bug" | "component" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task" | "template" | "unocss" | "user" | "worker">;
          default: string;
          required: true;
      };
  }>>, {
      name: "404" | "api" | "bug" | "component" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task" | "template" | "unocss" | "user" | "worker";
  }>;
  export const svgNames: ["404", "api", "bug", "component", "dashboard", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "link", "lock", "menu", "model-one", "model", "order-center", "order-convert", "order-list", "process-control", "process", "relation-graph", "relation-type", "resource", "role", "runner", "schedule", "search", "submit-order", "task-history", "task", "template", "unocss", "user", "worker"];
  export type SvgName = "404" | "api" | "bug" | "component" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "link" | "lock" | "menu" | "model-one" | "model" | "order-center" | "order-convert" | "order-list" | "process-control" | "process" | "relation-graph" | "relation-type" | "resource" | "role" | "runner" | "schedule" | "search" | "submit-order" | "task-history" | "task" | "template" | "unocss" | "user" | "worker";
  export default SvgIcon;
}
